---
title: "Laboration 2"
author: "Yinyi Yao Esbjörn Runesson"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_caption: true
---

# Sammanfattning
I detta inledande stycke ska du förklara vad labben går ut på, utan att gå in
på detaljer.



# Uppgift 1
1.1 
```{r}
z <- 1.72 # observerat värde på teststatistika
2 * (1- pnorm(z)) #p-värde för tvåsidigt test
1 - pnorm(z) # p-värde för ensidigt test

```
1.2
```{r}
t.test(1:10, alternative = "greater", mu = 4.5, conf.level = 0.9) #p-värde för nollhypotesen är 16,18%
t.test(1:10, alternative = "less", mu = 4.5, conf.level = 0.9) #p-värde för nollhypotesen är 83,82%
t.test(1:10, alternative = "two.sided", mu = 4.5, conf.level = 0.9) #p-värde för nollhypotesen är 32,35%
```
1.3
```{r}
#t.test(1:10, 1:10, alternative = "greater", mu = 4.5, conf.level = 0.9)

```


1.4
```{r}
t.test(1:10, 1:20, alternative = "greater", mu = 0, conf.level = 0.9) #p-värde för nollhypotesen är 99,76%
t.test(1:10, 1:20, alternative = "greater", mu = 0, var.equal = TRUE, conf.level = 0.9) #p-värde för nollhypotesen med Welch–Satterthwaites metod är 99,07%

```


# Uppgift 2
Mer text. Använd underrubriker för delfrågor om du tycker det är motiverat.

Et cetera om det är fler än 2 uppgifter.